### ISSUE TITLE
Provide image for linux/arm64/v8

### ISSUE THREAD

**Issue by freezer278** [mutagen-io/mutagen-compose-service#3]
To make this image run natively on Apple Silicon, please make this image on docker hub for linux/arm64/v8 architecture.

**Comment by xenoscopic** [comment]
I'll aim to tackle this as part of the transition to GitHub Actions.

**Comment by xenoscopic** [comment]
This is now completed with the CI changes made for Mutagen v0.12.0-beta4, and a linux/arm64/v8 build is available for the `mutagenio/sidecar:0.12.0-beta4` tag (along with all other Linux architectures besides S390x).

You'll have to update to v0.12.0-beta4 to take advantage of this, because the `latest` tag of the sidecar image (which is what Mutagen's Compose wrapper was previously referencing in v0.12.0-beta3 and earlier) won't be updated with a multiarch build and will be removed entirely (as using `latest` is not best practice) in about a month (once everyone has migrated off beta3 and earlier).
